Global:
  model_name: &model_name latin_PP-OCRv5_mobile_rec # To use static model for inference.
  debug: false
  use_gpu: true
  epoch_num: &epoch_num 75
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/french_PP-OCRv5_mobile_rec
  save_epoch_step: 10
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model: ../Data/Modèles/latin_PP-OCRv5_mobile_rec_pretrained.pdparams
  checkpoints:
  save_inference_dir: ./output/french_PP-OCRv5_mobile_rec/inference
  use_visualdl: false
  infer_img:
  character_dict_path: ../Data/french_dictv2.txt
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv5.txt
  d2s_train_image_shape: [3, 48, 320]
  uniform_output_enabled: true # pour sauvegarder un fichier json



Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: &model_type rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: 25

wandb:
  project: *model_name
  dir: ../wandb_runs
  tags: [*model_type]

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: ../dataset_sub_text_detection/
    ext_op_transform_idx: 1
    label_file_list:
    - ../dataset_sub_text_detection/rec_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: 25
    - RecAug:
    - MultiLabelEncode:
        max_text_length: 25
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[320, 32], [320, 48], [320, 64]]
    first_bs: &bs 128
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../dataset_sub_text_detection/
    label_file_list:
    - ../dataset_sub_text_detection/rec_val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        max_text_length: 1000
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        eval_mode: True
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4
